first version of search for country
Sythrill/CountryInfo pull request #1
Opened 2017-02-19 22:25 UTC by Sythrill

2017-02-20 06:46 UTC, matwjablonski requested changes

2017-02-20 06:46 UTC, matwjablonski commented on index.html
> +
empty lines to remove

2017-02-20 06:46 UTC, matwjablonski commented on script.js
> +var marker
add `;`

2017-02-20 20:52 UTC, Sythrill commented on index.html
> +
empty lines removed

2017-02-20 20:53 UTC, Sythrill commented on script.js
> +var marker
semicolon on its place

2017-02-21 21:23 UTC, matwjablonski approved these changes

2017-03-02 17:24 UTC, merged